services:
  app:
    build: .
    container_name: universal-table-engine
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
    volumes:
      - ./out:/app/out
    restart: unless-stopped
